### ISSUE TITLE
excel-samples - what to put into /SuiteScripts/Libraries/External folder?

### ISSUE THREAD

**Issue by gmihaylov** [nserpsolutions/public#1]
Hello,
can you supply files which are invoked by the requireConfig,

"jszip": "/SuiteScripts/Libraries/External/jszip", - dist/jszip.js
"xlsx": "/SuiteScripts/Libraries/External/xlsx" - https://github.com/SheetJS/sheetjs/blob/master/xlsx.js

I tried to download and put the official jszip and xlsx files in the Libraries/External but got:
TypeError: Cannot read property 'utils' of undefined [at createExcelFile

or just can you point me out what files the /SuiteScripts/Libraries/External is containing

**Comment by nserpsolutions** [comment]
Hi,

Please check https://github.com/nserpsolutions/csv-import/ for a working solution. I didn't review the latest build of the SheetJS but there may be some changes to the libraries.

**Comment by gmihaylov** [comment]
> Hi,
> 
> Please check https://github.com/nserpsolutions/csv-import/ for a working solution. I didn't review the latest build of the SheetJS but there may be some changes to the libraries.

Got them! Thanks!
